"""create_user_sessions_table

Revision ID: 12af922ab287
Revises: e85b467201c4
Create Date: 2025-12-02 11:58:27.530023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12af922ab287'
down_revision: Union[str, Sequence[str], None] = 'e85b467201c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_sessions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('device_name', sa.String(length=100), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('refresh_token', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('refresh_token'),
    schema='users'
    )
    op.create_index('idx_sessions_refresh_token', 'user_sessions', ['refresh_token'], unique=False, schema='users')
    op.create_index('idx_sessions_user_id', 'user_sessions', ['user_id'], unique=False, schema='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_sessions_user_id', table_name='user_sessions', schema='users')
    op.drop_index('idx_sessions_refresh_token', table_name='user_sessions', schema='users')
    op.drop_table('user_sessions', schema='users')
    # ### end Alembic commands ###
